# Converts `resume.md` to a PDF
name: Markdown to PDF

# Runs the job whenever there is a push to `main`
# Since this repo is so small, there is no need for branches thus `on pull`
on:
  push

# Dispatches a job
jobs:
  build:
    runs-on: ubuntu-latest

    # Moves repo to the runner
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    # Installs tools the runner to stitch the document
    - name: Install Pandoc and LaTeX
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex

    # Runs `pandoc` to perform the conversion
    - name: Convert Markdown to PDF
      run: pandoc -V geometry:margin=1in -V colorlinks:true -V pagestyle:empty resume.md -o resume.pdf

    # Pushes the PDF back to main
    - name: Push PDF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git fetch
        git checkout cv
        git pull origin
        git add resume.pdf
        git commit -m "Auto-generate PDF from resume.md"
        git push
