# Converts `resume.md` to a PDF
name: Markdown to PDF

# Runs the job whenever there is a push to `main`
# Since this repo is so small, there is no need for branches thus `on pull`
on:
  push:
    branches:
      - main

# Dispatches a job
jobs:
  build:
    runs-on: ubuntu-latest

    # Moves repo to the runner
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    # Installs tools the runner to stitch the document
    - name: Install Pandoc and LaTeX
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex

    # Runs `pandoc` to perform the conversion
    - name: Convert Markdown to PDF
      run: pandoc resume.md -o resume.pdf

    # Pushes the PDF back to main
    # We have to do a little dance to prevent recursive Actions from pushing onto main
    - name: Commit Dance PDF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout pdf-merge
        git pull origin pdf-merge
        git add resume.pdf
        git commit -m "Auto-generate PDF from resume.md"
        git push origin pdf-merge
        git checkout main
        git pull origin main
        git merge pdf-merge
